### PR TITLE
Set `ecmaVersion: 9` when parsing

### PR DESCRIPTION
**Pull request by goto-bus-stop**
This allows parsing `async function`s and other new JavaScript
features.

Thanks!

### CODE REVIEW

**Comment by twada** [comment]
@goto-bus-stop Thank you for your contribution!
I prefer [annual format](https://github.com/ternjs/acorn#main-parser) like `2016`,`2017` for `ecmaVersion` (`2018` in this case).
Once changed I'm 👍 to merge this.

**Comment by goto-bus-stop** [comment]
aight, done!

**Comment by twada** [comment]
@goto-bus-stop LGTM. Thanks!

**Comment by twada** [comment]
Released as [v2.1.0](https://github.com/unassert-js/unassertify/releases/tag/v2.1.0). Thank you @goto-bus-stop!

**Pull request merged**
